### ISSUE TITLE
Please add text alignment on message

### ISSUE THREAD

**Issue by MeGaPk** [NSExceptional/TBAlertController#9]

**Comment by ThePantsThief** [comment]
I cannot offer what UIAlertController does not offer.

**Comment by MeGaPk** [comment]
On my project, i used this: 
```
    __weak NSArray *viewArray = [[[[[[[[[[[[alertController view] subviews] firstObject] subviews] firstObject] subviews] firstObject] subviews] firstObject] subviews] firstObject] subviews];

    __weak UILabel *alertTitle = viewArray[0];
    alertTitle.textAlignment = NSTextAlignmentRight;

    __weak UILabel *alertMessage = viewArray[1];
    alertMessage.textAlignment = NSTextAlignmentLeft;
```

**Comment by ThePantsThief** [comment]
Sorry, exploring the subview hierarchy of the presented alert view to change the text alignment is not something I'm willing to implement since it would take *a lot* of work to support iOS 7, 8, and 9 using that method. There's a good chance the view layout changed with every version, and that it would break with iOS 10.

You're welcome to fork the project and implement this yourself though!
